#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other shells available, you may want to
#       try them.  Most people run this script with /bin/sh, but on some
#       systems an even fancier shell may be needed.
#
#   (2) The Java Virtual Machine used to run this script must have been
#       configured to not ignore input/output (see Security note below).
#
#   (3) Inspection of the ./gradlew file shows that it accepts Java options
#       after the last non-option argument.
#
#   Security note: The gradle wrapper always downloads a distribution of Gradle
#   from the network each time it's executed without the --offline flag.
#   This is intentional since it provides a fresh, known-good version of
#   Gradle. However, if you have concerns about network access, you can
#   use --offline to run with a previously downloaded version.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls##*' -> '}
    case $link in
      /*)
        app_path=$link
        ;;
      *)
        app_path=$APP_HOME$link
        ;;
    esac
done

# This is normally unused
APP_HOME=$(cd "${APP_HOME:-.}" && pwd -P) && export APP_HOME

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Run the Gradle wrapper
exec java \
    -Dorg.gradle.wrapper.properties=$APP_HOME/gradle/wrapper/gradle-wrapper.properties \
    -classpath $CLASSPATH \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"