package com.warranty.repository;

import com.warranty.entity.Category;
import com.warranty.entity.Product;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for ProductRepository.
 * Tests CRUD operations and custom query methods for warranty expiration filtering.
 */
@DataJpaTest
class ProductRepositoryTest {

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private CategoryRepository categoryRepository;

    private Category testCategory;

    @BeforeEach
    void setUp() {
        // Create a test category
        testCategory = categoryRepository.save(new Category("Electronics"));
    }

    @Test
    void testSaveProductWithAutoGeneratedId() {
        // Arrange
        Product product = new Product();
        product.setName("Laptop");
        product.setPurchaseDate(LocalDate.now().minusMonths(1));
        product.setWarrantyMonths(12);
        product.setCategory(testCategory);

        // Act
        Product savedProduct = productRepository.save(product);

        // Assert
        assertNotNull(savedProduct.getId());
        assertEquals("Laptop", savedProduct.getName());
        assertEquals(12, savedProduct.getWarrantyMonths());
    }

    @Test
    void testFindByIdWithValidId() {
        // Arrange
        Product product = new Product();
        product.setName("Phone");
        product.setPurchaseDate(LocalDate.now().minusMonths(2));
        product.setWarrantyMonths(24);
        product.setCategory(testCategory);
        Product savedProduct = productRepository.save(product);

        // Act
        Optional<Product> foundProduct = productRepository.findById(savedProduct.getId());

        // Assert
        assertTrue(foundProduct.isPresent());
        assertEquals(savedProduct.getId(), foundProduct.get().getId());
        assertEquals("Phone", foundProduct.get().getName());
    }

    @Test
    void testFindByIdWithInvalidId() {
        // Act
        Optional<Product> foundProduct = productRepository.findById(999L);

        // Assert
        assertTrue(foundProduct.isEmpty());
    }

    @Test
    void testFindAllReturnsAllSavedProducts() {
        // Arrange
        Product product1 = new Product();
        product1.setName("Laptop");
        product1.setPurchaseDate(LocalDate.now().minusMonths(1));
        product1.setWarrantyMonths(12);
        product1.setCategory(testCategory);

        Product product2 = new Product();
        product2.setName("Mouse");
        product2.setPurchaseDate(LocalDate.now().minusMonths(1));
        product2.setWarrantyMonths(6);
        product2.setCategory(testCategory);

        productRepository.save(product1);
        productRepository.save(product2);

        // Act
        List<Product> allProducts = productRepository.findAll();

        // Assert
        assertTrue(allProducts.size() >= 2);
        assertTrue(allProducts.stream().anyMatch(p -> p.getName().equals("Laptop")));
        assertTrue(allProducts.stream().anyMatch(p -> p.getName().equals("Mouse")));
    }

    @Test
    void testFindProductsExpiringWithinDate() {
        // Arrange
        LocalDate purchaseDate = LocalDate.now().minusMonths(11);
        LocalDate expiryDate = purchaseDate.plusMonths(12); // warranty expires in ~1 month

        Product expiringProduct = new Product();
        expiringProduct.setName("Expiring Product");
        expiringProduct.setPurchaseDate(purchaseDate);
        expiringProduct.setWarrantyMonths(12);
        expiringProduct.setCategory(testCategory);
        productRepository.save(expiringProduct);

        // Product with warranty that expires far in the future
        Product futureProduct = new Product();
        futureProduct.setName("Future Product");
        futureProduct.setPurchaseDate(LocalDate.now().minusMonths(1));
        futureProduct.setWarrantyMonths(36);
        futureProduct.setCategory(testCategory);
        productRepository.save(futureProduct);

        // Act
        LocalDate searchDate = LocalDate.now().plusDays(60);
        List<Product> expiringProducts = productRepository.findProductsExpiringWithin(searchDate);

        // Assert
        assertTrue(expiringProducts.stream().anyMatch(p -> p.getName().equals("Expiring Product")));
    }

    @Test
    void testFindProductsExpiringWithinEmptyResult() {
        // Arrange
        Product product = new Product();
        product.setName("New Product");
        product.setPurchaseDate(LocalDate.now().minusMonths(1));
        product.setWarrantyMonths(60); // warranty expires in ~5 years
        product.setCategory(testCategory);
        productRepository.save(product);

        // Act
        LocalDate searchDate = LocalDate.now().plusDays(10); // search within 10 days
        List<Product> expiringProducts = productRepository.findProductsExpiringWithin(searchDate);

        // Assert
        assertTrue(expiringProducts.isEmpty());
    }

    @Test
    void testDeleteProduct() {
        // Arrange
        Product product = new Product();
        product.setName("Product to Delete");
        product.setPurchaseDate(LocalDate.now().minusMonths(1));
        product.setWarrantyMonths(12);
        product.setCategory(testCategory);
        Product savedProduct = productRepository.save(product);
        Long productId = savedProduct.getId();

        // Act
        productRepository.deleteById(productId);

        // Assert
        Optional<Product> deletedProduct = productRepository.findById(productId);
        assertTrue(deletedProduct.isEmpty());
    }

    @Test
    void testHasAccessToInheritedCrudMethods() {
        // Arrange
        Product product = new Product();
        product.setName("CRUD Test Product");
        product.setPurchaseDate(LocalDate.now().minusMonths(1));
        product.setWarrantyMonths(12);
        product.setCategory(testCategory);

        // Act & Assert - testing that all inherited methods are accessible
        Product savedProduct = productRepository.save(product);
        assertNotNull(savedProduct.getId());

        Optional<Product> foundProduct = productRepository.findById(savedProduct.getId());
        assertTrue(foundProduct.isPresent());

        List<Product> allProducts = productRepository.findAll();
        assertTrue(allProducts.size() > 0);

        productRepository.delete(savedProduct);
        Optional<Product> deletedProduct = productRepository.findById(savedProduct.getId());
        assertTrue(deletedProduct.isEmpty());
    }
}
