package com.warranty.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

/**
 * Category entity representing a product category (e.g., Kitchen Appliances, Electronics).
 * Categories are used to classify products for organizational purposes.
 */
@Entity
@Table(name = "category")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Category {

    /**
     * Unique identifier for the category. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the category. Must be unique and cannot be null.
     */
    @Column(unique = true, nullable = false)
    private String name;

    /**
     * One-to-many relationship: a Category can have many Products.
     * Products are mapped by the 'category' field in the Product entity.
     */
    @OneToMany(mappedBy = "category")
    private Set<Product> products;

    /**
     * Custom constructor to create a Category with just a name.
     * @param name the name of the category
     */
    public Category(String name) {
        this.name = name;
    }
}
