package com.warranty.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Product entity representing an item owned by the user with warranty tracking information.
 * Each product belongs to exactly one Category and tracks its purchase date and warranty duration.
 */
@Entity
@Table(name = "product")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Product {

    /**
     * Unique identifier for the product. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product. Cannot be null or empty.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Date when the product was purchased. Cannot be null.
     */
    @Column(nullable = false)
    private LocalDate purchaseDate;

    /**
     * Warranty duration in months. Cannot be null and must be greater than zero.
     */
    @Column(nullable = false)
    private Integer warrantyMonths;

    /**
     * Many-to-one relationship: a Product belongs to exactly one Category.
     * Uses lazy loading to avoid unnecessary data loading.
     * Foreign key is stored as category_id in the product table.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;
}
